stages:
  - validate
  - deploy
  - cleanup

variables:
  SCRIPT_NAME: clean-aws_alert.sh

# Check if everything is ready before deployment
validate:
  stage: validate
  image: amazonlinux:latest
  
  script:
    - echo "🔍 Checking if required files exist..."
    
    # Check if script exists
    - |
      if [ ! -f "$SCRIPT_NAME" ]; then
        echo "❌ Error: $SCRIPT_NAME not found!"
        exit 1
      fi
      echo "✅ Script found: $SCRIPT_NAME"
    
    # Check if YAML input file exists
    - |
      if [ -f "aws_vms.yaml" ]; then
        echo "✅ Found YAML input file: aws_vms.yaml"
      else
        echo "❌ Error: aws_vms.yaml file not found!"
        echo "Please create aws_vms.yaml with your EC2 instances"
        exit 1
      fi
    
    - echo "✅ Validation passed - ready to deploy!"
    
  only:
    - main

# Create CloudWatch alarms
create_aws_vm_alerts:
  stage: deploy
  image: amazonlinux:latest
  
  before_script:
    # Install required tools
    - yum update -y
    - yum install -y unzip curl jq python3 python3-pip wget
    
    # Install yq for YAML parsing
    - wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    - chmod +x /usr/local/bin/yq
    
    # Install AWS CLI
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip && ./aws/install
    
    # Set up AWS credentials
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    
  script:
    # Run the cleaned AWS alert script
    - chmod +x $SCRIPT_NAME
    - ./$SCRIPT_NAME
    
  after_script:
    # Show simple summary
    - |
      if [ -f "aws_alerts_output.json" ]; then
        echo "✅ Alarms created successfully!"
        echo "📄 Results saved to aws_alerts_output.json"
      else
        echo "⚠️ Warning: No output file created"
      fi
    
  artifacts:
    paths:
      - aws_alerts_output.json
      - aws_alerts.log
    expire_in: 1 week
    
  when: manual
  only:
    - main

# Clean up temporary files
cleanup:
  stage: cleanup
  image: amazonlinux:latest
  
  script:
    - echo "🧹 Cleaning up temporary files..."
    - rm -f awscliv2.zip
    - rm -f *.tmp
    - echo "✅ Cleanup completed!"
    
  when: always
  only:
    - main
